server:
  port: 9003


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: BANK-SERVICE
        uri: lb://BANK-SERVICE/
        predicates:
        - Path=/api/bankservice/**
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE/
        predicates:
        - Path=/api/orderservice/**,/api/bankservice/**
      - id: USER-SERVICE
        uri: lb://user-service/
        predicates:
        - Path=/users/**,/api/orderservice/**,/api/bankservice/** 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
     hostname: localhost   